=== riegeroliver/HiggsAnalysis-CombinedLimit/data/xml/RooDYHistShape.dtd
<!ELEMENT Histogram (Data+)>
<!ATTLIST Histogram
          Version           CDATA            #IMPLIED
	  >

<!ELEMENT Data (Bin+)>
<!ATTLIST Data
          Name              CDATA            #REQUIRED
	  Min               CDATA            #REQUIRED
	  Max               CDATA            #REQUIRED
	  BinWidth          CDATA            #REQUIRED
	  > 

<!ELEMENT Bin EMPTY>
<!ATTLIST Bin
          X                 CDATA            #REQUIRED
          Y                 CDATA            #REQUIRED
	  >

=== riegeroliver/HiggsAnalysis-CombinedLimit/data/xml/EPS_DY_LO.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE Histogram SYSTEM "RooDYHistShape.dtd">
<Histogram Version="hist/DYHist.root">
  <Data Name="DY_LO" Min="100.0" Max="250.0" BinWidth="0.1">
    <Bin X="100.05" Y="0.5315453154479391"/>
    <Bin X="100.14999999999999" Y="0.5173897294737541"/>
    <Bin X="100.25" Y="0.5038291438708415"/>
    <Bin X="100.35" Y="0.49082974844802196"/>
    <Bin X="100.45" Y="0.4783600297295455"/>
    <Bin X="100.55" Y="0.4663906055793821"/>
    <Bin X="100.64999999999999" Y="0.4548940706394139"/>
    <Bin X="100.75" Y="0.44384485217157854"/>
    <Bin X="100.85" Y="0.4332190758521508"/>
    <Bin X="100.95" Y="0.422994441038764"/>
    <Bin X="101.05" Y="0.4131501050131914"/>
    <Bin X="101.14999999999999" Y="0.4036665756943159"/>
    <Bin X="101.25" Y="0.39452561231597355"/>
    <Bin X="101.35" Y="0.38571013356997624"/>
    <Bin X="101.45" Y="0.3772041327248225"/>
    <Bin X="101.55" Y="0.36899259924688105"/>
    <Bin X="101.64999999999999" Y="0.36106144646731336"/>
    <Bin X="101.75" Y="0.3533974448590426"/>
    <Bin X="101.85" Y="0.345988160509293"/>
    <Bin X="101.95" Y="0.33882189839598664"/>
    <Bin X="102.05" Y="0.3318876500991464"/>
    <Bin X="102.14999999999999" Y="0.32517504560153526"/>
    <Bin X="102.25" Y="0.31867430885559095"/>
    <Bin X="102.35" Y="0.31237621681586164"/>
    <Bin X="102.45" Y="0.3062720616576151"/>
    <Bin X="102.55" Y="0.3003536159229394"/>
    <Bin X="102.64999999999999" Y="0.2946131003554983"/>
    <Bin X="102.75" Y="0.28904315420307386"/>
    <Bin X="102.85" Y="0.28363680778528066"/>
    <Bin X="102.95" Y="0.27838745713957536"/>
    <Bin X="103.05" Y="0.2732888405745072"/>
    <Bin X="103.14999999999999" Y="0.268335016972809"/>
    <Bin X="103.25" Y="0.26352034570079175"/>
    <Bin X="103.35" Y="0.2588394679919183"/>
    <Bin X="103.45" Y="0.25428728968417763"/>
    <Bin X="103.55" Y="0.24985896520139073"/>
    <Bin X="103.64999999999999" Y="0.24554988267698713"/>
    <Bin X="103.75" Y="0.24135565012905597"/>
    <Bin X="103.85" Y="0.23727208260175345"/>
    <Bin X="103.95" Y="0.23329519019699368"/>
    <Bin X="104.05" Y="0.22942116692554892"/>
    <Bin X="104.14999999999999" Y="0.2256463803138169"/>
    <Bin X="104.25" Y="0.22196736170729153"/>
    <Bin X="104.35" Y="0.2183807972173917"/>
    <Bin X="104.45" Y="0.21488351926226026"/>
    <Bin X="104.55" Y="0.2114724986567091"/>
    <Bin X="104.64999999999999" Y="0.208144837210364"/>
    <Bin X="104.75" Y="0.20489776079594604"/>
    <Bin X="104.85" Y="0.201728612853471"/>
    <Bin X="104.95" Y="0.19863484829831501"/>
    <Bin X="105.05" Y="0.19561402780450296"/>
    <Bin X="105.14999999999999" Y="0.1926638124358633"/>
    <Bin X="105.25" Y="0.1897819586010889"/>
    <Bin X="105.35" Y="0.18696631330952532"/>
    <Bin X="105.45" Y="0.18421480970726345"/>
    <Bin X="105.55" Y="0.1815254628741916"/>
    <Bin X="105.64999999999999" Y="0.17889636586409693"/>
    <Bin X="105.75" Y="0.17632568597196452"/>
    <Bin X="105.85" Y="0.17381166121284877"/>
    <Bin X="105.95" Y="0.17135259699880098"/>
    <Bin X="106.05" Y="0.16894686300063338"/>
    <Bin X="106.14999999999999" Y="0.16659289018282586"/>
    <Bin X="106.25" Y="0.16428916800024945"/>
    <Bin X="106.35" Y="0.16203424174682385"/>
    <Bin X="106.45" Y="0.1598267100461129"/>
    <Bin X="106.55" Y="0.1576652224754427"/>
    <Bin X="106.64999999999999" Y="0.15554847731510205"/>
    <Bin X="106.75" Y="0.153475219415003"/>
    <Bin X="106.85" Y="0.1514442381718897"/>
    <Bin X="106.95" Y="0.1494543656100694"/>
    <Bin X="107.05" Y="0.14750447456007656"/>
    <Bin X="107.14999999999999" Y="0.14559347692897376"/>
    <Bin X="107.25" Y="0.14372032205729326"/>
    <Bin X="107.35" Y="0.1418839951573949"/>
    <Bin X="107.45" Y="0.14008351582878834"/>
    <Bin X="107.55" Y="0.1383179366457425"/>
    <Bin X="107.64999999999999" Y="0.13658634181346915"/>
    <Bin X="107.75" Y="0.13488784588870592"/>
    <Bin X="107.85" Y="0.13322159256129137"/>
    <Bin X="107.95" Y="0.13158675349351381"/>
    <Bin X="108.05" Y="0.12998252721360481"/>
    <Bin X="108.14999999999999" Y="0.1284081380611489"/>
    <Bin X="108.25" Y="0.12686283518091337"/>
    <Bin X="108.35" Y="0.1253458915630114"/>
    <Bin X="108.45" Y="0.1238566031267292"/>
    <Bin X="108.55" Y="0.12239428784573121"/>
    <Bin X="108.64999999999999" Y="0.12095828491256623"/>
    <Bin X="108.75" Y="0.11954795394040138"/>
    <Bin X="108.85" Y="0.11816267419999814"/>
    <Bin X="108.95" Y="0.11680184389031353"/>
    <Bin X="109.05" Y="0.11546487944082015"/>
    <Bin X="109.14999999999999" Y="0.11415121484407835"/>
    <Bin X="109.25" Y="0.11286030101704696"/>
    <Bin X="109.35" Y="0.11159160518964656"/>
    <Bin X="109.45" Y="0.11034461031927827"/>
    <Bin X="109.55" Y="0.10911881453003698"/>
    <Bin X="109.64999999999999" Y="0.1079137305753623"/>
    <Bin X="109.75" Y="0.10672888532312602"/>
    <Bin X="109.85" Y="0.10556381926189562"/>
    <Bin X="109.95" Y="0.10441808602753111"/>
    <Bin X="110.05" Y="0.10329125194911315"/>
    <Bin X="110.14999999999999" Y="0.10218289561317886"/>
    <Bin X="110.25" Y="0.10109260744562322"/>
    <Bin X="110.35" Y="0.10001998931027048"/>
    <Bin X="110.45" Y="0.0989646541234024"/>
    <Bin X="110.55" Y="0.09792622548357227"/>
    <Bin X="110.64999999999999" Y="0.09690433731590936"/>
    <Bin X="110.75" Y="0.09589863353033769"/>
    <Bin X="110.85" Y="0.09490876769307041"/>
    <Bin X="110.95" Y="0.09393440271074051"/>
    <Bin X="111.05" Y="0.09297521052667279"/>
    <Bin X="111.14999999999999" Y="0.09203087182872272"/>
    <Bin X="111.25" Y="0.09110107576817737"/>
    <Bin X="111.35" Y="0.09018551968927152"/>
    <Bin X="111.45" Y="0.08928390886880125"/>
    <Bin X="111.55" Y="0.08839595626545356"/>
    <Bin X="111.64999999999999" Y="0.08752138227841781"/>
    <Bin X="111.75" Y="0.0866599145148705"/>
    <Bin X="111.85" Y="0.08581128756598136"/>
    <Bin X="111.95" Y="0.08497524279107072"/>
    <Bin X="112.05" Y="0.08415152810957473"/>
    <Bin X="112.14999999999999" Y="0.08333989780051425"/>
    <Bin X="112.25" Y="0.08254011230911011"/>
    <Bin X="112.35" Y="0.08175193806032408"/>
    <Bin X="112.45" Y="0.08097514727897608"/>
    <Bin X="112.55" Y="0.08020951781619463"/>
    <Bin X="112.64999999999999" Y="0.07945483298196652"/>
    <Bin X="112.75" Y="0.07871088138349927"/>
    <Bin X="112.85" Y="0.07797745676919751"/>
    <Bin X="112.95" Y="0.07725435787801918"/>
    <Bin X="113.05" Y="0.07654138829398904"/>
    <Bin X="113.14999999999999" Y="0.07583835630568256"/>
    <Bin X="113.25" Y="0.07514507477047597"/>
    <Bin X="113.35" Y="0.07446136098338142"/>
    <Bin X="113.45" Y="0.07378703655029027"/>
    <Bin X="113.55" Y="0.07312192726544325"/>
    <Bin X="113.64999999999999" Y="0.07246586299298591"/>
    <Bin X="113.75" Y="0.07181867755244106"/>
    <Bin X="113.85" Y="0.07118020860794283"/>
    <Bin X="113.95" Y="0.07055029756110512"/>
    <Bin X="114.05" Y="0.06992878944739338"/>
    <Bin X="114.14999999999999" Y="0.06931553283582652"/>
    <Bin X="114.25" Y="0.06871037973195528"/>
    <Bin X="114.35" Y="0.06811318548392006"/>
    <Bin X="114.45" Y="0.06752380869154045"/>
    <Bin X="114.55" Y="0.06694211111828058"/>
    <Bin X="114.64999999999999" Y="0.06636795760600038"/>
    <Bin X="114.75" Y="0.06580121599240718"/>
    <Bin X="114.85" Y="0.06524175703107896"/>
    <Bin X="114.95" Y="0.06468945431399448"/>
    <Bin X="115.05" Y="0.06414418419646789"/>
    <Bin X="115.14999999999999" Y="0.06360582572440067"/>
    <Bin X="115.25" Y="0.06307426056377732"/>
    <Bin X="115.35" Y="0.06254937293231759"/>
    <Bin X="115.45" Y="0.0620310495332156"/>
    <Bin X="115.55" Y="0.061519179490886144"/>
    <Bin X="115.64999999999999" Y="0.06101365428866154"/>
    <Bin X="115.75" Y="0.06051436770834855"/>
    <Bin X="115.85" Y="0.06002121577161032"/>
    <Bin X="115.95" Y="0.05953409668308449"/>
    <Bin X="116.05" Y="0.059052910775195575"/>
    <Bin X="116.14999999999999" Y="0.058577560454598894"/>
    <Bin X="116.25" Y="0.05810795015019225"/>
    <Bin X="116.35" Y="0.057643986262661276"/>
    <Bin X="116.45" Y="0.05718557711548763"/>
    <Bin X="116.55" Y="0.05673263290738198"/>
    <Bin X="116.64999999999999" Y="0.05628506566609565"/>
    <Bin X="116.75" Y="0.05584278920355746"/>
    <Bin X="116.85" Y="0.05540571907229582"/>
    <Bin X="116.95" Y="0.05497377252311089"/>
    <Bin X="117.05" Y="0.054546868463942876"/>
    <Bin X="117.14999999999999" Y="0.054124927419906085"/>
    <Bin X="117.25" Y="0.053707871494453115"/>
    <Bin X="117.35" Y="0.05329562433162226"/>
    <Bin X="117.45" Y="0.05288811107934692"/>
    <Bin X="117.55" Y="0.05248525835377948"/>
    <Bin X="117.64999999999999" Y="0.05208699420460951"/>
    <Bin X="117.75" Y="0.0516932480813358"/>
    <Bin X="117.85" Y="0.05130395080046667"/>
    <Bin X="117.95" Y="0.05091903451361931"/>
    <Bin X="118.05" Y="0.050538432676484224"/>
    <Bin X="118.14999999999999" Y="0.05016208001864179"/>
    <Bin X="118.25" Y="0.049789912514183375"/>
    <Bin X="118.35" Y="0.04942186735313423"/>
    <Bin X="118.45" Y="0.04905788291363612"/>
    <Bin X="118.55" Y="0.048697898734878224"/>
    <Bin X="118.64999999999999" Y="0.048341855490743775"/>
    <Bin X="118.75" Y="0.04798969496416018"/>
    <Bin X="118.85" Y="0.0476413600221245"/>
    <Bin X="118.95" Y="0.04729679459138429"/>
    <Bin X="119.05" Y="0.04695594363475779"/>
    <Bin X="119.14999999999999" Y="0.04661875312807418"/>
    <Bin X="119.25" Y="0.04628517003770675"/>
    <Bin X="119.35" Y="0.04595514229869827"/>
    <Bin X="119.45" Y="0.04562861879343792"/>
    <Bin X="119.55" Y="0.04530554933090026"/>
    <Bin X="119.64999999999999" Y="0.0449858846264041"/>
    <Bin X="119.75" Y="0.04466957628189596"/>
    <Bin X="119.85" Y="0.04435657676672961"/>
    <Bin X="119.95" Y="0.04404683939893522"/>
    <Bin X="120.05" Y="0.04374031832695894"/>
    <Bin X="120.14999999999999" Y="0.043436968511863815"/>
    <Bin X="120.25" Y="0.043136745709974125"/>
